on:
    push:
      branches:
        - main
env:
    AWS_REGION: us-east-1
    ECR_REPOSITORY: testaction
    ECS_SERVICE: mytestservice
    ECS_CLUSTER: myclustertest
    CONTAINER_NAME: "testactioncontainer"
jobs:
    deploy:
      name: Deploy
      runs-on: ubuntu-latest
      environment: development
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up JDK 11
          uses: actions/setup-java@v4 
          with:
            distribution: 'temurin'
            java-version: '11'
  
        - name: Build Spring Boot application
          run: mvn clean install

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4 
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_ID1 }}
            aws-region: ${{env.AWS_REGION}}

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2 
    
        - name: Build, tag, and push the image to Amazon ECR
          id: build-image
          env:
              ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
              ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
          run: |
              docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
              docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
              echo "IMAGE=$ECR_REGISTRY/$ECR_REPOSITORY:latest" >> $GITHUB_ENV

        - name: Install AWS CLI
          run: |
                  if ! command -v aws &> /dev/null; then
                  curl -sSf "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                  unzip awscliv2.zip
                  sudo ./aws/install
                  else
                  aws --version
                  aws --version 2>&1 | grep "aws-cli/2."
                  if [ $? -eq 0 ]; then
                      echo "AWS CLI version 2 is already installed."
                  else
                      echo "Updating AWS CLI..."
                      curl -sSf "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                      unzip awscliv2.zip
                      sudo ./aws/install --update
                  fi
                  fi

        - name: Download task definition 
          run: |
            aws ecs describe-task-definition --task-definition mytesttd --query taskDefinition > task-definition.json
        
        - name: Fill in new image ID in task definition
          id: task-def
          uses: aws-actions/amazon-ecs-render-task-definition@v1
          with:
              task-definition: task-definition.json
              container-name: ${{ env.CONTAINER_NAME }}
              image: ${{ env.IMAGE }}
        
        - name: Deploy Amazon ECS task definition
          uses: aws-actions/amazon-ecs-deploy-task-definition@v1
          with:
                task-definition: ${{ steps.task-def.outputs['task-definition'] }}
                service: ${{ env.ECS_SERVICE }}
                cluster: ${{ env.ECS_CLUSTER }}